name: Asset Management Apis Package

on:
  push:
    branches:
      - main
    paths:
      - "fe/**"
      - ".github/workflows/cd.yml"

jobs:
  publish-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/ou-food-order-admin:latest ./be

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/ou-food-order-admin:latest
